#!/usr/bin/env python3
"""
Pro Tools Key Detection - Detect the musical key of audio files.

Analyzes audio files using chroma features and the Krumhansl-Schmuckler
key-finding algorithm. Outputs results compatible with Pro Tools session
workflows on Windows.

Usage:
    python key_detector.py song.wav
    python key_detector.py --batch "C:/Sessions/MyProject/*.wav"
    python key_detector.py song.mp3 --format marker --output markers.txt
"""

import argparse
import csv
import glob
import json
import os
import sys
from pathlib import Path

import librosa
import numpy as np


# Krumhansl-Schmuckler key profiles
# Major and minor profiles for correlating chroma vectors against known key signatures
MAJOR_PROFILE = np.array([6.35, 2.23, 3.48, 2.33, 4.38, 4.09,
                          2.52, 5.19, 2.39, 3.66, 2.29, 2.88])
MINOR_PROFILE = np.array([6.33, 2.68, 3.52, 5.38, 2.60, 3.53,
                          2.54, 4.75, 3.98, 2.69, 3.34, 3.17])

NOTE_NAMES = ['C', 'C#', 'D', 'D#', 'E', 'F',
              'F#', 'G', 'G#', 'A', 'A#', 'B']

# Enharmonic spellings preferred in Pro Tools / standard music notation
ENHARMONIC_MAP = {
    'C#': 'Db', 'D#': 'Eb', 'F#': 'Gb', 'G#': 'Ab', 'A#': 'Bb'
}


def detect_key(audio_path: str, sr: int = 22050, use_harmonic: bool = True) -> dict:
    """Detect the musical key of an audio file.

    Args:
        audio_path: Path to the audio file (WAV, MP3, FLAC, AIFF, etc.)
        sr: Sample rate for analysis.
        use_harmonic: If True, isolate harmonic content before analysis
                      for better accuracy on percussive material.

    Returns:
        Dictionary with key, mode, confidence, correlation scores, and alternates.
    """
    y, sr = librosa.load(audio_path, sr=sr, mono=True)

    if use_harmonic:
        y = librosa.effects.harmonic(y, margin=4.0)

    # Compute chroma energy using CQT for better frequency resolution
    chroma = librosa.feature.chroma_cqt(y=y, sr=sr, n_chroma=12, bins_per_octave=36)
    chroma_avg = np.mean(chroma, axis=1)

    # Normalize
    chroma_avg = chroma_avg / (np.linalg.norm(chroma_avg) + 1e-8)

    # Correlate with all 24 major/minor key profiles
    scores = []
    for i in range(12):
        major_shifted = np.roll(MAJOR_PROFILE, i)
        minor_shifted = np.roll(MINOR_PROFILE, i)

        major_corr = np.corrcoef(chroma_avg, major_shifted)[0, 1]
        minor_corr = np.corrcoef(chroma_avg, minor_shifted)[0, 1]

        scores.append((NOTE_NAMES[i], 'major', float(major_corr)))
        scores.append((NOTE_NAMES[i], 'minor', float(minor_corr)))

    scores.sort(key=lambda x: x[2], reverse=True)

    best = scores[0]
    key_name = best[0]
    mode = best[1]
    confidence = best[2]

    # Build display name with enharmonic preference
    display_key = ENHARMONIC_MAP.get(key_name, key_name) if mode == 'minor' else key_name
    if mode == 'major' and key_name in ENHARMONIC_MAP:
        display_key = ENHARMONIC_MAP[key_name]

    # Camelot wheel code for DJ/mixing compatibility
    camelot = _camelot_code(key_name, mode)

    # Top 3 alternates
    alternates = []
    for note, m, corr in scores[1:4]:
        alt_display = ENHARMONIC_MAP.get(note, note)
        alternates.append({
            'key': f"{alt_display} {m}",
            'correlation': round(corr, 4),
        })

    return {
        'file': os.path.basename(audio_path),
        'path': str(Path(audio_path).resolve()),
        'key': display_key,
        'mode': mode,
        'key_label': f"{display_key} {mode}",
        'camelot': camelot,
        'confidence': round(confidence, 4),
        'alternates': alternates,
        'chroma_vector': [round(float(c), 4) for c in chroma_avg],
    }


def _camelot_code(note: str, mode: str) -> str:
    """Convert key + mode to Camelot wheel notation."""
    major_map = {
        'C': '8B', 'G': '9B', 'D': '10B', 'A': '11B', 'E': '12B', 'B': '1B',
        'F#': '2B', 'C#': '3B', 'G#': '4B', 'D#': '5B', 'A#': '6B', 'F': '7B',
    }
    minor_map = {
        'A': '8A', 'E': '9A', 'B': '10A', 'F#': '11A', 'C#': '12A', 'G#': '1A',
        'D#': '2A', 'A#': '3A', 'F': '4A', 'C': '5A', 'G': '6A', 'D': '7A',
    }
    if mode == 'major':
        return major_map.get(note, '?')
    return minor_map.get(note, '?')


def format_protools_markers(results: list[dict]) -> str:
    """Format results as a Pro Tools marker/memory location import file.

    Pro Tools can import session text files with marker information.
    This generates tab-delimited marker data.
    """
    lines = [
        "HEADER",
        "# Pro Tools Key Detection Markers",
        f"# Generated by key_detector.py",
        "",
        "MARKER\tLOCATION\tTIME REFERENCE\tUNITS\tNAME\tCOMMENTS",
    ]
    for i, r in enumerate(results, 1):
        name = f"Key: {r['key_label']}"
        comment = f"Camelot: {r['camelot']} | Confidence: {r['confidence']}"
        lines.append(f"{i}\t00:00:00.000\t0\tSamples\t{name}\t{comment}")

    return '\n'.join(lines)


def format_csv(results: list[dict]) -> str:
    """Format results as CSV for spreadsheet or DAW import."""
    import io
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(['File', 'Key', 'Mode', 'Camelot', 'Confidence',
                     'Alt 1', 'Alt 2', 'Alt 3'])
    for r in results:
        alts = [a['key'] for a in r.get('alternates', [])]
        while len(alts) < 3:
            alts.append('')
        writer.writerow([
            r['file'], r['key'], r['mode'], r['camelot'],
            r['confidence'], *alts[:3],
        ])
    return output.getvalue()


def format_json(results: list[dict]) -> str:
    """Format results as JSON."""
    return json.dumps(results, indent=2)


def format_text(results: list[dict]) -> str:
    """Format results as human-readable text."""
    lines = []
    for r in results:
        lines.append(f"  File:       {r['file']}")
        lines.append(f"  Key:        {r['key_label']}")
        lines.append(f"  Camelot:    {r['camelot']}")
        lines.append(f"  Confidence: {r['confidence']}")
        if r['alternates']:
            alt_str = ', '.join(a['key'] for a in r['alternates'])
            lines.append(f"  Alternates: {alt_str}")
        lines.append("")
    return '\n'.join(lines)


FORMATTERS = {
    'text': format_text,
    'json': format_json,
    'csv': format_csv,
    'marker': format_protools_markers,
}


def main():
    parser = argparse.ArgumentParser(
        description='Detect musical key of audio files for Pro Tools integration.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s track.wav
  %(prog)s --batch "C:\\Sessions\\*.wav" --format csv --output keys.csv
  %(prog)s track.mp3 --format marker --output session_markers.txt
  %(prog)s track.wav --format json
        """,
    )
    parser.add_argument('files', nargs='*', help='Audio file(s) to analyze')
    parser.add_argument('--batch', type=str,
                        help='Glob pattern for batch processing (e.g. "*.wav")')
    parser.add_argument('--format', choices=FORMATTERS.keys(), default='text',
                        help='Output format (default: text)')
    parser.add_argument('--output', '-o', type=str,
                        help='Write output to file instead of stdout')
    parser.add_argument('--sr', type=int, default=22050,
                        help='Sample rate for analysis (default: 22050)')
    parser.add_argument('--no-harmonic', action='store_true',
                        help='Skip harmonic isolation (faster but less accurate)')

    args = parser.parse_args()

    # Collect files
    audio_files = list(args.files) if args.files else []
    if args.batch:
        audio_files.extend(glob.glob(args.batch))

    if not audio_files:
        parser.error('No audio files specified. Provide file paths or use --batch.')

    # Deduplicate while preserving order
    seen = set()
    unique_files = []
    for f in audio_files:
        resolved = str(Path(f).resolve())
        if resolved not in seen:
            seen.add(resolved)
            unique_files.append(f)

    # Analyze each file
    results = []
    for filepath in unique_files:
        if not os.path.isfile(filepath):
            print(f"Warning: Skipping '{filepath}' (not found)", file=sys.stderr)
            continue

        try:
            print(f"Analyzing: {filepath}...", file=sys.stderr)
            result = detect_key(filepath, sr=args.sr, use_harmonic=not args.no_harmonic)
            results.append(result)
        except Exception as e:
            print(f"Error analyzing '{filepath}': {e}", file=sys.stderr)

    if not results:
        print("No files were successfully analyzed.", file=sys.stderr)
        sys.exit(1)

    # Format and output
    formatter = FORMATTERS[args.format]
    output = formatter(results)

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(output, encoding='utf-8')
        print(f"Results written to: {args.output}", file=sys.stderr)
    else:
        print(output)


if __name__ == '__main__':
    main()
